#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    config_load dns-warmup
    config_get_bool enabled main enabled 1
    [ "$enabled" = 1 ] || return 0

    procd_open_instance
    procd_set_param command /usr/bin/dns-warmup.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn_retry 0
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger dns-warmup
}
